#!/usr/bin/expect
#!/bin/sh

set arg1 [lindex $argv 0]

set timeout 10
spawn /usr/local/bin/ti clean 
expect "Project cleaned successfully"
spawn echo "cleaned project"
set timeout 60
spawn ti build args -b
expect "or platform name"
send "2\r"
expect "Project built successfully"
set timeout 20
spawn calabash-ios setup build/iphone/
expect "Please answer yes (y) or no (n)"  { send "n\r" }
expect "Default target: ${arg1}"  {  send "\r" }
expect "Setup done"

