source 'http://rubygems.org'
#gem 'run_loop', '~> 0.2.1'
gem 'calabash-android', '0.5.0'
gem 'calabash-cucumber', '0.11.0'
#gem "calabash-android", "0.5.1"
#gem "calabash-cucumber", "0.10.0.pre1"
gem 'multi_json', '1.7.9'
gem 'rspec', '1.3.0'
gem 'rubyXL'
gem 'nokogiri'
gem 'differ'
gem 'virtus'
gem 'xml-simple'
gem 'unicode_utils'
gem 'rickshaw'
gem 'require_all'
#gem 'calabash_shared'
