source 'http://rubygems.org'
gem 'calabash-cucumber', '0.12.3'
gem 'calabash-android', '~> 0.5.7'
gem 'nokogiri'
gem 'differ'
gem 'xml-simple'
#gem 'virtus'
#gem 'xml-simple'
gem 'unicode_utils'
gem 'rickshaw'
gem 'require_all'
#gem 'calabash_shared'
