# config/cucumber.yml

<% common_path = "-r features/common/support -r features/common/strings -r features/tests/step_definitions -r features/BasePages/Default" %>

<% common_settings_ios = " -f 'Slowhandcuke::Formatter' PLATFORM=ios -f json -o features/report/report.json" %>
<% common_settings_android = " -f 'Slowhandcuke::Formatter'  PLATFORM=android -f json -o features/report/report.json " %>

<% ios_specific_path = " -r features/ios/support -r features/ios/modules " %>
<% android_specific_path = "-r features/android/support -r features/android/modules" %>

<% de_mt_ios_specific_path = " -r features/BasePages/de" %>
<% de_mt_android_specific_path = " -r features/BasePages/de" %>

<% en_fc_ios_specific_path = " -r features/ios/modules-r features/BasePages/uk" %>
<% en_fc_android_specific_path = " -r features/BasePages/uk" %>

<% en_tm_ios_specific_path = " -r features/BasePages/uk" %>
<% en_tm_android_specific_path = "  -r features/BasePages/uk" %>

<% nor_ios_specific_path = " -r features/ios/modules/nor -r features/BasePages/nor" %>
<% nor_android_specific_path = " -r features/android/modules/nor -r features/BasePages/nor" %>


#DEBUG=1 CALABASH_FULL_CONSOLE_OUTPUT=1
de_mt_ios:   <%= common_settings_ios %> <%= common_path %>  <%= ios_specific_path %> <%= de_mt_ios_specific_path %>
de_mt_android:  <%= common_settings_android %> <%= common_path %>  <%= android_specific_path %> <%= de_mt_android_specific_path %>

de_mt_ios:   <%= common_settings_ios %> <%= common_path %>  <%= ios_specific_path %> <%= de_mt_ios_specific_path %>
de_mt_android:  <%= common_settings_android %> <%= common_path %>  <%= android_specific_path %> <%= de_mt_android_specific_path %>


en_fc_ios: <%= common_settings_ios %> <%= common_path %>  <%= ios_specific_path %> <%= en_fc_ios_specific_path %>
en_fc_android: <%= common_settings_android %> <%= common_path %>  <%= android_specific_path %> <%= en_fc_android_specific_path %>


en_th_ios: <%= common_settings_ios %> <%= common_path %>  <%= ios_specific_path %> <%= en_tm_ios_specific_path %>
en_th_android: <%= common_settings_android %> <%= common_path %>  <%= android_specific_path %> <%= en_tm_android_specific_path %>

nor_android: <%= common_settings_android %> <%= common_path %>  <%= android_specific_path %> <%= nor_android_specific_path %>
nor_ios: <%= common_settings_ios %>  <%= common_path %>  <%= ios_specific_path %> <%= nor_ios_specific_path %>