sv:
  weekdays:
    Monday: "Måndag"
    Tuesday: "Tisdag"
    Wednesday: "Onsdag"
    Thursday: "Torsdag"
    Friday: "Fredag"
    Saturday: "Lördag"
    Sunday: "Söndag"
  months:
    January: "januari"
    February: "februari"
    March: "mars"
    April: "april"
    May: "maj"
    June: "juni"
    July: "juli"
    August: "augusti"
    September: "september"
    October: "oktober"
    November: "november"
    December: "december"

no:
  weekdays:
    Monday: "Mandag"
    Tuesday: "Tirsdag"
    Wednesday: "Onsdag"
    Thursday: "Torsdag"
    Friday: "Fredag"
    Saturday: "Lørdag"
    Sunday: "Søndag"
  months:
    January: "januar"
    February: "februar"
    March: "mars"
    April: "april"
    May: "mai"
    June: "juni"
    July: "juli"
    August: "august"
    September: "september"
    October: "oktober"
    November: "november"
    December: "desember"

da:
  weekdays:
    Monday: "Mandag"
    Tuesday: "Tirsdag"
    Wednesday: "Onsdag"
    Thursday: "Torsdag"
    Friday: "Fredag"
    Saturday: "Lørdag"
    Sunday: "Søndag"
  months:
    January: "januar"
    February: "februar"
    March: "marts"
    April: "april"
    May: "maj"
    June: "juni"
    July: "juli"
    August: "august"
    September: "september"
    October: "oktober"
    November: "november"
    December: "december"

de:
  weekdays:
    Monday: "Montag"
    Tuesday: "Dienstag"
    Wednesday: "Mittwoch"
    Thursday: "Donnerstag"
    Friday: "Freitag"
    Saturday: "Samstag"
    Sunday: "Sonntag"
  months:
    January: "Januar"
    February: "Februar"
    March: "März"
    April: "April"
    May: "Mai"
    June: "Juni"
    July: "Juli"
    August: "August"
    September: "September"
    October: "Oktober"
    November: "November"
    December: "Dezember"

fi:
  weekdays:
    Monday: "maanantai"
    Tuesday: "tiistai"
    Wednesday: "keskiviikko"
    Thursday: "torstai"
    Friday: "perjantai"
    Saturday: "lauantai"
    Sunday: "sunnuntai"
  months:
    January: "tammikuu"
    February: "helmikuu"
    March: "maaliskuu"
    April: "huhtikuu"
    May: "saattaa"
    June: "kesäkuu"
    July: "heinäkuu"
    August: "elokuu"
    September: "syyskuu"
    October: "lokakuu"
    November: "marraskuu"
    December: "joulukuu"